// Code generated by mockery v2.23.4. DO NOT EDIT.

package external_system_activation

import (
	external_system_activation "github.com/odch/go-capzlog/client/external_system_activation"
	mock "github.com/stretchr/testify/mock"

	runtime "github.com/go-openapi/runtime"
)

// MockClientService is an autogenerated mock type for the ClientService type
type MockClientService struct {
	mock.Mock
}

type MockClientService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientService) EXPECT() *MockClientService_Expecter {
	return &MockClientService_Expecter{mock: &_m.Mock}
}

// ExternalSystemActivationPost provides a mock function with given fields: params, authInfo, opts
func (_m *MockClientService) ExternalSystemActivationPost(params *external_system_activation.ExternalSystemActivationPostParams, authInfo runtime.ClientAuthInfoWriter, opts ...external_system_activation.ClientOption) (*external_system_activation.ExternalSystemActivationPostOK, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, params, authInfo)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *external_system_activation.ExternalSystemActivationPostOK
	var r1 error
	if rf, ok := ret.Get(0).(func(*external_system_activation.ExternalSystemActivationPostParams, runtime.ClientAuthInfoWriter, ...external_system_activation.ClientOption) (*external_system_activation.ExternalSystemActivationPostOK, error)); ok {
		return rf(params, authInfo, opts...)
	}
	if rf, ok := ret.Get(0).(func(*external_system_activation.ExternalSystemActivationPostParams, runtime.ClientAuthInfoWriter, ...external_system_activation.ClientOption) *external_system_activation.ExternalSystemActivationPostOK); ok {
		r0 = rf(params, authInfo, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*external_system_activation.ExternalSystemActivationPostOK)
		}
	}

	if rf, ok := ret.Get(1).(func(*external_system_activation.ExternalSystemActivationPostParams, runtime.ClientAuthInfoWriter, ...external_system_activation.ClientOption) error); ok {
		r1 = rf(params, authInfo, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientService_ExternalSystemActivationPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExternalSystemActivationPost'
type MockClientService_ExternalSystemActivationPost_Call struct {
	*mock.Call
}

// ExternalSystemActivationPost is a helper method to define mock.On call
//   - params *external_system_activation.ExternalSystemActivationPostParams
//   - authInfo runtime.ClientAuthInfoWriter
//   - opts ...external_system_activation.ClientOption
func (_e *MockClientService_Expecter) ExternalSystemActivationPost(params interface{}, authInfo interface{}, opts ...interface{}) *MockClientService_ExternalSystemActivationPost_Call {
	return &MockClientService_ExternalSystemActivationPost_Call{Call: _e.mock.On("ExternalSystemActivationPost",
		append([]interface{}{params, authInfo}, opts...)...)}
}

func (_c *MockClientService_ExternalSystemActivationPost_Call) Run(run func(params *external_system_activation.ExternalSystemActivationPostParams, authInfo runtime.ClientAuthInfoWriter, opts ...external_system_activation.ClientOption)) *MockClientService_ExternalSystemActivationPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]external_system_activation.ClientOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(external_system_activation.ClientOption)
			}
		}
		run(args[0].(*external_system_activation.ExternalSystemActivationPostParams), args[1].(runtime.ClientAuthInfoWriter), variadicArgs...)
	})
	return _c
}

func (_c *MockClientService_ExternalSystemActivationPost_Call) Return(_a0 *external_system_activation.ExternalSystemActivationPostOK, _a1 error) *MockClientService_ExternalSystemActivationPost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientService_ExternalSystemActivationPost_Call) RunAndReturn(run func(*external_system_activation.ExternalSystemActivationPostParams, runtime.ClientAuthInfoWriter, ...external_system_activation.ClientOption) (*external_system_activation.ExternalSystemActivationPostOK, error)) *MockClientService_ExternalSystemActivationPost_Call {
	_c.Call.Return(run)
	return _c
}

// SetTransport provides a mock function with given fields: transport
func (_m *MockClientService) SetTransport(transport runtime.ClientTransport) {
	_m.Called(transport)
}

// MockClientService_SetTransport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTransport'
type MockClientService_SetTransport_Call struct {
	*mock.Call
}

// SetTransport is a helper method to define mock.On call
//   - transport runtime.ClientTransport
func (_e *MockClientService_Expecter) SetTransport(transport interface{}) *MockClientService_SetTransport_Call {
	return &MockClientService_SetTransport_Call{Call: _e.mock.On("SetTransport", transport)}
}

func (_c *MockClientService_SetTransport_Call) Run(run func(transport runtime.ClientTransport)) *MockClientService_SetTransport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(runtime.ClientTransport))
	})
	return _c
}

func (_c *MockClientService_SetTransport_Call) Return() *MockClientService_SetTransport_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClientService_SetTransport_Call) RunAndReturn(run func(runtime.ClientTransport)) *MockClientService_SetTransport_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientService creates a new instance of MockClientService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientService {
	mock := &MockClientService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
