name: Deploy (prod)
'on':
  push:
    tags:
      - 'v*'  # Triggers when a tag like v1.0.0 is pushed
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - prod
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Install Google Cloud SDK components
        run: |
          sudo apt-get install google-cloud-cli

      - name: Configure Google Cloud Project
        run: |
          gcloud config set project ${{ vars.FIREBASE_PROJECT }}

      - name: Deploy Firebase Function (Go)
        run: |
          gcloud functions deploy syncPilotLogBook \
            --gen2 \
            --region europe-west1 \
            --runtime go124 \
            --entry-point SyncPilotLogBook \
            --trigger-location eur3 \
            --trigger-event-filters="type=google.cloud.firestore.document.v1.written" \
            --trigger-event-filters="database=(default)" \
            --trigger-event-filters-path-pattern="document=pilotLogbookSync/{sync}" \
            --set-env-vars=CAPZLOG_HOST=${{ vars.CAPZLOG_HOST }}
          gcloud functions deploy activatePilotLogBookSync \
            --gen2 \
            --region europe-west1 \
            --runtime go124 \
            --entry-point ActivatePilotLogBookSync \
            --trigger-location eur3 \
            --trigger-event-filters="type=google.cloud.firestore.document.v1.written" \
            --trigger-event-filters="database=(default)" \
            --trigger-event-filters-path-pattern="document=users/{user}" \
            --set-env-vars=CAPZLOG_HOST=${{ vars.CAPZLOG_HOST }}
          gcloud functions deploy SyncPilotLookbookWebhook \
            --gen2 \
            --region europe-west1 \
            --runtime go124 \
            --entry-point SyncPilotLookbookWebhook \
            --trigger-http \
            --set-env-vars=CAPZLOG_HOST=${{ vars.CAPZLOG_HOST }}
